spring.application.name=sicei

#Driver configuration

spring.datasource.url=jdbc:postgresql://${IP_DATABASE}:5432/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

#Optional to debug
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

##### AWS - S3 #####
aws.s3.bucket=sicei-charly
aws.region=us-east-1

aws.accessKeyId=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}
aws.sessionToken=${AWS_SESSION_TOKEN}

